from pydantic import BaseModel


class GenerateRequest(BaseModel):
    prompt: str


class GenerateResponse(BaseModel):
    answer: str
    confidence: float
    reasoning_summary: str


class FakeProvider:
    def generate(self, prompt: str) -> GenerateResponse:
        return GenerateResponse(
            answer=f"Stub answer for: {prompt}",
            confidence=0.81,
            reasoning_summary="Generated by the module service fake provider.",
        )


provider = FakeProvider()


def generate(payload: GenerateRequest) -> GenerateResponse:
    return provider.generate(payload.prompt)
